# This workflow will ensure that all changes to the goldenmaster are tested

name: Technology Template Build Test

on:
  pull_request:
    paths:
      - 'goldenmaster/**'
    branches: [main]

jobs:
  conan_build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Conan Windows Latest MSVC", os: windows-latest }
          - { name: "Conan Ubuntu Latest GCC", os: ubuntu-latest }
          - { name: "Conan macOS Latest Clang", os: macos-latest }
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache conan on Windows
        uses: actions/cache@v3
        if: ${{ matrix.config.os == 'windows-latest'}}
        with:
          path: |
            ~\.conan\data
          key: ${{ matrix.config.os }}-conan-cache-${{ hashFiles('goldenmaster/**/conanfile.py', 'goldenmaster/**/conanfile.txt') }}
          restore-keys: |
            ${{ matrix.config.os }}-conan-cache
      - name: Cache conan on Linux/macOS
        uses: actions/cache@v3
        if: ${{ matrix.config.os != 'windows-latest'}}
        with:
          path: |
            ~/.conan/data
          key: ${{ matrix.config.os }}-conan-cache-${{ hashFiles('goldenmaster/**/conanfile.py', 'goldenmaster/**/conanfile.txt') }}
          restore-keys: |
            ${{ matrix.config.os }}-conan-cache
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: "pip"
          cache-dependency-path: ".github/workflows/conan-requirements.txt"
      - name: Install Conan
        run: pip install -r .github/workflows/conan-requirements.txt
      - name: Create default profile
        run: conan profile new default --detect
      - name: Set C++11 on Linux
        if: ${{ matrix.config.os == 'ubuntu-latest'}}
        run: conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: Set Debug and runtime on Windows
        if: ${{ matrix.config.os == 'windows-latest'}}
        run: |
          conan profile update settings.compiler.runtime=MDd default
          conan profile update settings.build_type=Debug default
      - name: Install CMake
        run: conan install cmake/3.24.2@ -g=virtualrunenv --build=missing
      - name: Run conan build Linux/macOS
        if: ${{ matrix.config.os != 'windows-latest'}}
        working-directory: goldenmaster
        run: chmod +x ./test_conan.sh && ./test_conan.sh
      - name: Run conan build Windows
        if: ${{ matrix.config.os == 'windows-latest'}}
        working-directory: goldenmaster
        run: cmd.exe /c 'test_conan.bat'

  cmake_build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "CMake Ubuntu Latest GCC", os: ubuntu-latest }
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo apt-get install -y cmake libpoco-dev nlohmann-json3-dev
      - name: Install catch2
        run: git clone --branch v2.13.8 --depth 1 https://github.com/catchorg/Catch2.git && cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install
      - name: Run cmake
        working-directory: goldenmaster
        run: cmake -Bbuild -H. -DCMAKE_INSTALL_PREFIX=tmp -DBUILD_TESTING=ON && cmake --build build/ && cmake --build build/ --target test && cmake --build build/ --target install
