# This workflow will ensure that the goldenmaster is always up-to-date before being merged

name: Technology Template Goldenmaster Test

on:
  pull_request:
    branches: [main]

env:
  GITHUB_AUTH_TOKEN: ${{ secrets.WOLFGANG_REPO_PACKAGE_READ }}
  GOPRIVATE: "github.com/apigear-io/*"
  GH_ACCESS_TOKEN: ${{ secrets.APIGEAR_REPOS }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  go_version: "1.19.x"
  
jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: arduino/setup-task@v1          
      - run: task install
      - run: task diff
      - name: Install clang-format-12
        run: sudo apt-get install --no-install-recommends -y clang-format-12 && sudo mv /usr/bin/clang-format-12 /usr/bin/clang-format
