# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Technology Template Publish

on: 
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Is this a test run? No artifacts will be published'
        required: true
        default: 'true'
      lernaVersionIncrement:
        description: 'Set the semver keyword or explicit version for the templates packages(e.g. minor, patch or 2.0.3). This will be applied to all packages!'
        required: false
        default: 'minor'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_AUTH_TOKEN: ${{ secrets.WOLFGANG_REPO_PACKAGE_READ }}
      GCP_AUTH_TOKEN: ${{ secrets.GCP_GITHUB_CICD_TECH_TEMPLATE_ACCOUNT_TOKEN }}

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
        # pulls all tags (needed for lerna / semantic release to correctly version)
      - run: git fetch --prune --unshallow --tags

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # see https://classic.yarnpkg.com/en/docs/cli/install
      - run: yarn install --frozen-lockfile --link-duplicates
      - run: yarn run test:goldenmaster
      - name: Configure Git User
        run: |
          git config --global user.email "ci@apigear.io"
          git config --global user.name "@$GITHUB_ACTOR"
      - name: Dry run lerna version
        if: ${{ github.event.inputs.dryRun == 'true' }}
        run: |
          yarn run lerna version --yes ${{ github.event.inputs.lernaVersionIncrement }} --no-push
      - name: Publish packages
        if: ${{ github.event.inputs.dryRun != 'true' }}
        run: |
          yarn run lerna version --yes ${{ github.event.inputs.lernaVersionIncrement }}
          yarn run lerna publish --conventional-commits
